version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/local/Dockerfile
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=MYSQL
      - REDIS_HOST=REDIS
      - PRONTO_OAUTH_CLIENT_SECRET=
      - PRONTO_OAUTH_CLIENT_ID=
      - APP_URL=
      - PRONTO_URL=https://chat.pronto.io
    command: >
      bash -c "
        /wait-for-it.sh --timeout=30 mysql:3306
        php artisan --env=docker migrate
        /usr/sbin/apachectl -D FOREGROUND
        "
    ports:
      - "8000:80"
  redis:
    image: redis
  mysql:
    image: mysql/mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=pronto
    volumes:
      - ./.docker/local/initialize_db.sql:/docker-entrypoint-initdb.d/initialize_db.sql
    ports:
      - "3306:3306"
